EasyMission-web/src/main/java/tn/esprit/EasyMission/presentation/mbeans/AppUserBean.java
package tn.esprit.EasyMission.presentation.mbeans;

import java.io.Serializable;
import java.util.List;


import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.view.ViewScoped;

import tn.esprit.EasyMission.Business.AppUserService;
import tn.esprit.EasyMission.Entity.AppUser;
import tn.esprit.EasyMission.Entity.Role;

@ManagedBean
@ViewScoped
public class AppUserBean implements Serializable{

	private String prenom;
	private String nom;
	private String password;
	private String email;
	private int phone;
	private boolean isActif;
	private Role role;
	private List<AppUser> users;
	private Integer usIdToBeUpdated;
	
	

	@EJB
	AppUserService usService;



	
	public int addUser(){
		
		 return usService.ajouterUser(new AppUser(nom, prenom, email, phone, isActif, role, password));
	   
	}
	
	public List<AppUser> getUsers() {
		users = usService.getUsers();
		return users;
	}
	
	public void supprimer(Integer usId){
		usService.removeUser(usId);
	}
	
	public void modifier(AppUser us){
		this.setEmail(us.getEmail());
		this.setPassword(us.getPassword());
		this.setPhone(us.getPhone());
		this.setActif(us.getIsActif());
		this.setPrenom(us.getPrenom());
		this.setNom(us.getNom());
		this.setRole(us.getRole());
		this.setUsIdToBeUpdated(us.getId());
	//	String navigateTo = "/Welcome?faces-redirect=true";
	//	return navigateTo;
	}
	
	public void mettreAjourUser(){
		usService.updateUser(new AppUser(usIdToBeUpdated, nom, prenom, email, phone,isActif, role, password));
	}
	
	public String getPrenom() {
		return prenom;
	}



	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}



	public String getNom() {
		return nom;
	}



	public void setNom(String nom) {
		this.nom = nom;
	}



	public String getPassword() {
		return password;
	}



	public void setPassword(String password) {
		this.password = password;
	}



	public String getEmail() {
		return email;
	}



	public void setEmail(String email) {
		this.email = email;
	}



	public int getPhone() {
		return phone;
	}



	public void setPhone(int phone) {
		this.phone = phone;
	}



	public boolean isActif() {
		return isActif;
	}



	public void setActif(boolean isActif) {
		this.isActif = isActif;
	}



	public Role getRole() {
		return role;
	}



	public void setRole(Role role) {
		this.role = role;
	}



	public Integer getUsIdToBeUpdated() {
		return usIdToBeUpdated;
	}



	public void setUsIdToBeUpdated(Integer usIdToBeUpdated) {
		this.usIdToBeUpdated = usIdToBeUpdated;
	}



	public AppUserService getUsService() {
		return usService;
	}



	public void setUsService(AppUserService usService) {
		this.usService = usService;
	}

	public void setUsers(List<AppUser> users) {
		this.users = users;
	}
	
	
	
	
}

EasyMission-web/src/main/java/tn/esprit/EasyMission/presentation/mbeans/JobBean.java
package tn.esprit.EasyMission.presentation.mbeans;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.SimpleFormatter;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.BarChartModel;
import org.primefaces.model.chart.ChartSeries;

import tn.esprit.EasyMission.Business.ApplimentService;
import tn.esprit.EasyMission.Business.JobVolenteerService;
import tn.esprit.EasyMission.Entity.AppUser;
import tn.esprit.EasyMission.Entity.Appliement;
import tn.esprit.EasyMission.Entity.JobVolenteer;
import tn.esprit.EasyMission.Entity.User;
import tn.esprit.EasyMission.iBusiness.IAppliment;
import tn.esprit.EasyMission.iBusiness.IJobVolenteerServiceLocal;
import tn.esprit.EasyMission.iBusiness.IUserServiceLocal;





@ManagedBean(name="adbean")
@SessionScoped
public class JobBean {
	
	
	@EJB
    ApplimentService  applimentService	 ;
	
	
	@EJB
	IJobVolenteerServiceLocal js ;
	
	@EJB
	IUserServiceLocal us ;
	
	@EJB
	IAppliment<Appliement> pew ;
	
	private Integer idJobV;
	private Integer idJobV1;

	private String Titre;
	private String Titre1;
	
	private Date DateDebut;
	private Date DateDebut1;

	private Date DateFin;
	private String Lieu;

	private String Lieu1;
	
private String Description;
private String Description1;

private String Taches;
private String Taches1;

private String picture;
private UploadedFile uploadedFile;

private UploadedFile ui;

	HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
	//session.setAttribute("user", user);

AppUser us1;

	private List<User> users ;
	
	private String text="" ;

	
	private List<JobVolenteer> jobs ;
	private List<User> oo = new ArrayList<User>();


	List<JobVolenteer> ll ;
	JobVolenteer j = new JobVolenteer();
	JobVolenteer jj = new JobVolenteer();
	 BarChartModel barModel ;
	
	@PostConstruct
	public void init(){
		us1= (AppUser)session.getAttribute("user");
		jobs=js.findAll(JobVolenteer.class);
	}
	
	public void hetJobss(){
		jobs=js.findAll(JobVolenteer.class);
		
	}
	
	
	public List<JobVolenteer> doSearchJob(String x)
	
	{ 
		System.out.println("lllllllllllllllllllllllllloooooooooooooooooooooo       p:"+x);

		
		if(x==""){
			ll=jobs ;
			System.out.println("aaaaaaaaaaaaaaaaaaaaaywah");
			x="";
		}
		else
		{
			ll=js.SearchJobVolenteer(x);
			x=null;
			System.out.println("opopopopopopoopopooo"+x);
		}
		
		return ll ;
	}
	
	public void doCreateJob() {
		
	//	System.out.println("jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"+ui.getFileName());
		/*String fileName = uploadedFile.getFileName();
		String contentType = uploadedFile.getContentType();
		System.out.println("fileName : " + fileName + " contentType : " + contentType);
		byte[] contents = uploadedFile.getContents();
		this.setPicture(contents);*/
		
		//SimpleDateFormat simpFormat = new SimpleDateFormat("dd-MM-yyyy");
		//String navigateTo = "/todos?faces-redirect=true";
		j.setTitre(Titre);
		//j.setDateDebut(DateDebut);
		//j.setDateFin(DateFin);
		
		j.setDateDebut(DateDebut);
		j.setDateFin(DateFin);
		j.setLieu(Lieu);
		j.setDescription(Description);
		j.setTaches(Taches);
		//j.setPicture(name);
		j.setImage(name);
		
		//if ((j.getDateFin().before(j.getDateDebut()))&&(j.getDateFin().before(new Date())))
		if (j.getDateFin().before(j.getDateDebut()))
		{
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,"Error","please check your dates"));	
		}
		else
		{
		js.add(j);
		
		}
		hetJobss();
		js.send();
	
	}
	
	
	public void gotoupdateJOB(String i) throws IOException {
		FacesContext.getCurrentInstance().getExternalContext().redirect("updateJOB.jsf");
		int j = Integer.parseInt(i) ;
		JobVolenteer v = js.findById(JobVolenteer.class, j);
		idJobV1=v.getIdJobV();
		Titre1=v.getTitre();
		Lieu1=v.getLieu();
		Description1=v.getDescription();
		Taches1=v.getTaches();
		DateDebut1=v.getDateDebut();
		
		
	
	}
	public void updateJOB(String i)throws IOException {
		int j = Integer.parseInt(i) ;
		JobVolenteer v = js.findById(JobVolenteer.class, j);
		
		v.setTitre(Titre1);
		
		v.setLieu(Lieu1);
		v.setDescription(Description1);
		v.setTaches(Taches1);	
		js.update(v);
		FacesContext.getCurrentInstance().getExternalContext().redirect("showjobsAdmin.jsf");
		hetJobss();
		
		
	
	}
	public void DeleteJOB(String i) throws IOException{
		int j = Integer.parseInt(i) ;
		JobVolenteer v = js.findById(JobVolenteer.class, j);
		
		js.removeById(JobVolenteer.class, j);
		FacesContext.getCurrentInstance().getExternalContext().redirect("showjobsAdmin.jsf");

		hetJobss();
		
		
	
	}
	public void bbJOB() throws IOException{
		//List<Appliement> po = pew.getBestVolenteerUser();
	//	System.out.println("*****************************************"+po.size());
		

		int s=0 ;
		Map<AppUser,Integer> po =pew.getBestVolenteerUser();
		for (AppUser mapKey : po.keySet()) {
			// utilise ici hashMap.get(mapKey) pour accéder aux valeurs
			System.out.println("ffffffffffffffffffff "+po.get(mapKey));
			s=po.get(mapKey);
			
		}
		List<JobVolenteer> ps= pew.allparticipation();
		int l =ps.size();
		barModel = new BarChartModel();
		 ChartSeries boys = new ChartSeries();
	        boys.setLabel("Boys");
	        boys.set("Jobs", l);
	       
	 
	        ChartSeries girls = new ChartSeries();
	        girls.setLabel("max Jobs made by single user");
	        girls.set("Jobs",s);
	        
	        barModel.addSeries(boys);
	        barModel.addSeries(girls);
	        barModel.setTitle("Bar Chart");
	        barModel.setLegendPosition("ne");
	         
	        Axis xAxis = barModel.getAxis(AxisType.X);
	        xAxis.setLabel("jobs");
	         
	        Axis yAxis = barModel.getAxis(AxisType.Y);
	        yAxis.setLabel("quantity");
	        yAxis.setMin(0);
	        yAxis.setMax(10);
		
	        FacesContext.getCurrentInstance().getExternalContext().redirect("piechart.jsf");
	}
	
	public List<JobVolenteer> searchJobVolenter(String param)
	{
		return js.SearchJobVolenteer(param);
	}
	

	
	
	
	
	
	public void handleFileUpload(FileUploadEvent event) {
		name= event.getFile()
				.getFileName();
		FacesMessage message = new FacesMessage("Succesful", event.getFile()
				.getFileName() + " is uploaded.");
		FacesContext.getCurrentInstance().addMessage(null, message);
	
		
	//	C:\Users\aloulou\workspaceTest\backup\EasyMission\EasyMission\EasyMission-web\src\main\webapp\ressources\img
	
		
		//C:\Users\aloulou\workspaceTest\backup\EasyMission\EasyMission\EasyMission-web\src\main\webapp\ressources\img	
		String localPath = "C:" 
		        + File.separator + "Users"
				+ File.separator+ "aloulou" 
				+ File.separator + "workspaceTest" 
				+ File.separator + "backup" 
				+ File.separator + "EasyMission"
				+ File.separator + "EasyMission"
				+ File.separator + "EasyMission-web"
				+ File.separator + "src" 
				+ File.separator + "main"
				+ File.separator + "webapp" 
				+ File.separator + "ressources"
				+ File.separator + "img" 
				+ File.separator + name ;


	
		ExternalContext externalContext = FacesContext.getCurrentInstance()
				.getExternalContext();
		String filepath = externalContext.getRealPath("") + File.separator
				+ "ressources" + File.separator + "img" + File.separator + name ;

		try (

		InputStream input = event.getFile().getInputstream()) {
			OutputStream os = new FileOutputStream(localPath);
			OutputStream osServer = new FileOutputStream(localPath);
			byte[] b = new byte[2048];
			int length;

			while ((length = input.read(b)) != -1) {
				os.write(b, 0, length);
				osServer.write(b, 0, length);
			}

			input.close();
			os.close();
			osServer.close();

		} catch (IOException e) {
			// Show faces message?
		}

	}


String name ;
    public UploadedFile getFile() {
		return file;
	}

	public void setFile(UploadedFile file) {
		this.file = file;
	}

	private UploadedFile file;
	
	
	
	
	
	
	
	
	
	
	public UploadedFile getUploadedFile() {
		return uploadedFile;
	}

	public void setUploadedFile(UploadedFile uploadedFile) {
		this.uploadedFile = uploadedFile;
	}

	

	public String getPicture() {
		return picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getIdJobV1() {
		return idJobV1;
	}

	public void setIdJobV1(Integer idJobV1) {
		this.idJobV1 = idJobV1;
	}

	public String getTitre1() {
		return Titre1;
	}

	public void setTitre1(String titre1) {
		Titre1 = titre1;
	}

	public String getLieu1() {
		return Lieu1;
	}

	public void setLieu1(String lieu1) {
		Lieu1 = lieu1;
	}

	public String getDescription1() {
		return Description1;
	}

	public void setDescription1(String description1) {
		Description1 = description1;
	}

	public String getTaches1() {
		return Taches1;
	}

	public void setTaches1(String taches1) {
		Taches1 = taches1;
	}

	public IUserServiceLocal getUs() {
		return us;
	}

	public void setUs(IUserServiceLocal us) {
		this.us = us;
	}

	public List<User> getOo() {
		return oo;
	}

	public void setOo(List<User> oo) {
		this.oo = oo;
	}

	public JobVolenteer getJj() {
		return jj;
	}

	public void setJj(JobVolenteer jj) {
		this.jj = jj;
	}

EasyMission-web/src/main/java/tn/esprit/EasyMission/presentation/mbeans/LoginBean.java
package tn.esprit.EasyMission.presentation.mbeans;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import tn.esprit.EasyMission.Business.AppUserService;
import tn.esprit.EasyMission.Business.ApplimentService;
import tn.esprit.EasyMission.Entity.AppUser;
import tn.esprit.EasyMission.Entity.Role;

@ManagedBean
@SessionScoped
public class LoginBean {
	
	private String login;
	private String password;
	private static AppUser us;
	private boolean loggedIn;
	
	
	
	
	@EJB
	AppUserService usService;
	
	@EJB
    ApplimentService  applimentService	 ;
	
	public String doLogin(){
		String navigateTo = "null";
		us = usService.getUsersByEmailAndPassword(login, password);
		if (us != null && us.getRole() == Role.administrateur){
			navigateTo = "/pages/Register?faces-redirect=true";
		    loggedIn = true;
		} else {
			FacesContext.getCurrentInstance().addMessage("form:btn", new FacesMessage("bad credentials"));
		}
	return navigateTo;

	}

	public String doLogout(){
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
	    return "/pages/Login?faces-redirect=true";
	}
	
	
	public String getLogin() {
		return login;
	}
	public void setLogin(String login) {
		this.login = login;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public static AppUser getUs() {
		return us;
	}
	public void setUs(AppUser us) {
		this.us = us;
	}
	public boolean isLoggedIn() {
		return loggedIn;
	}
	public void setLoggedIn(boolean loggedIn) {
		this.loggedIn = loggedIn;
	}
	

    public boolean resOrNot(int trainingId, int userId) {
    	return applimentService.verifUserResOrNot(trainingId, userId);
}
    
	
	 public void cancelReservation(int trainingId){
	  	  applimentService.annulerReservation(trainingId,LoginBean.getUs().getId());
	  	}
	
	
	
}

EasyMission-web/src/main/java/tn/esprit/EasyMission/presentation/mbeans/UserMangementBean.java
package tn.esprit.EasyMission.presentation.mbeans;



import java.io.Serializable;

import javax.ejb.EJB;
//import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import tn.esprit.EasyMission.Entity.AppUser;
import tn.esprit.EasyMission.iBusiness.IAppUserServiceRemote;


@ManagedBean
@SessionScoped
public class UserMangementBean implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	IAppUserServiceRemote basicOpsLocal ;
	
	private Boolean loggedInAsAgent = false;
	private AppUser user = new AppUser();
	private boolean isLogged;

	public String logout() {
		isLogged = false;
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		return "/login?faces-redirect=true";
	}
	public String doLogin() {
		String navigateTo = "";
		AppUser userLoggedIn = basicOpsLocal.authentification(user.getNom(), user.getPassword());
		if (userLoggedIn != null) {
			isLogged = true;
			user = userLoggedIn;
			HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
			session.setAttribute("user", user);
			
			AppUser us1= (AppUser)session.getAttribute("user");
		//	System.out.println("oooooooooooooooooooooooooooooooooooooooooooooooooo "+us1.getFirstname());
			if (userLoggedIn instanceof AppUser) {
				navigateTo = "/iFrame/add?faces-redirect=true";
			}else {
				loggedInAsAgent = true;
				navigateTo = "/iFrame/showClient?faces-redirect=true";
			
				}
		} else {
			loggedInAsAgent = false;
			navigateTo = "erreur?faces-redirect=true";
		
			System.err.println("not");
		}
		return navigateTo;
	}
	
	
	
	public IAppUserServiceRemote getBasicOpsLocal() {
		return basicOpsLocal;
	}
	public void setBasicOpsLocal(IAppUserServiceRemote basicOpsLocal) {
		this.basicOpsLocal = basicOpsLocal;
	}
	public Boolean getLoggedInAsAgent() {
		return loggedInAsAgent;
	}
	public void setLoggedInAsAgent(Boolean loggedInAsAgent) {
		this.loggedInAsAgent = loggedInAsAgent;
	}
	public AppUser getUser() {
		return user;
	}
	public void setUser(AppUser user) {
		this.user = user;
	}
	public boolean isLogged() {
		return isLogged;
	}
	public void setLogged(boolean isLogged) {
		this.isLogged = isLogged;
	}


}

EasyMission-web/src/main/webapp/Login.xhtml
a<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
	<title>Login </title>
</h:head>
<body>
<h2>Login </h2>
	<br />
<h:form id="form">
<h:panelGrid columns="2">
<h:outputText value="login"/>
<h:inputText value="#{loginBean.login}" />
<h:outputText value="password" />
<h:inputSecret value="#{loginBean.password}" />
<h:commandButton id="btn" action="#{loginBean.doLogin()}" value="login" />
<h:message for="btn"/>
</h:panelGrid>
</h:form>
</body>
</html>

EasyMission-web/src/main/webapp/Register.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Register</title>
</h:head>
<h:body>
	<h2>Register </h2>
	<br />
<h:form id="form">
			<h:panelGrid columns="2">
				<h:outputText value="login (email)" />
				<h:inputText value="#{appUserBean.email}" />

				<h:outputText value="password" />
				<h:inputSecret value="#{appUserBean.password}" />

				<h:outputText value="nom" />
				<h:inputText value="#{appUserBean.nom}" />

				<h:outputText value="prenom" />
				<h:inputText value="#{appUserBean.prenom}" />

                <h:outputText value="phone" />
				<h:inputText value="#{appUserBean.phone}" />

				<h:outputText value="Actif / Inactif" />
				<h:selectBooleanCheckbox value="#{appUserBean.actif}" />

				<h:outputText value="Role" />
				<h:selectOneMenu value="#{appUserBean.role}">
					<f:selectItem itemLabel="Selectionner le role" itemValue="" />
					<f:selectItems value="#{dataRole.roles}" />
				</h:selectOneMenu>
				<h:commandButton action="#{appUserBean.addUser()}"
					value="Register" />
				<h:commandButton action="#{appUserBean.mettreAjourUser()}"
					value="Mettre ton profil à jour" />
			</h:panelGrid>
		</h:form>
		<h:form>
			<h:commandButton action="#{loginBean.doLogout()}" value="logout" />
		</h:form>
		<h:dataTable value="#{appUserBean.users}" var="us" border="1">
			<h:column>
				<f:facet name="header">
					<h:outputText value="login" />
				</f:facet>
				<h:outputText value="#{us.email}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="nom" />
				</f:facet>
				<h:outputText value="#{us.nom}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="prenom" />
				</f:facet>
				<h:outputText value="#{us.prenom}" />
			</h:column>

            <h:column>
				<f:facet name="header">
					<h:outputText value="phone" />
				</f:facet>
				<h:outputText value="#{us.phone}" />
			</h:column>
			
			<h:column>
				<f:facet name="header">
					<h:outputText value="role" />
				</f:facet>
				<h:outputText value="#{us.role}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Actif" />
				</f:facet>
				<h:outputText value="#{us.isActif == true ? 'Oui' : 'Non'}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Action" />
				</f:facet>
				<h:form>
					<h:commandButton action="#{appUserBean.supprimer(us.id)}"
						value="Supprimer" />
					<h:commandButton action="#{appUserBean.modifier(us)}"
						value="Modifier" />
				</h:form>
			</h:column>
		</h:dataTable>
		</h:body>
		</html>

EasyMission-web/src/main/webapp/ShowJobs.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	   xmlns:f="http://xmlns.jcp.org/jsf/core"
	   xmlns:h="http://xmlns.jcp.org/jsf/html"
	   xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	   xmlns:jsf="http://xmlns.jcp.org/jsf"
	   xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	   xmlns:p="http://primefaces.org/ui">
	   


		  
		
<h:head>

	
	
	<title>add new Job</title>
<h:outputScript library="primefaces" name="jquery/jquery.js" target="head" />
<h:outputScript library="primefaces" name="jquery/jquery-plugins.js" target="head" />
	<script type="text/javascript" src="resources/js/main.js">
	</script>
</h:head>

<h:body>
<h2>
 JOB DETAILS </h2>





<h:form id="form">
     <p:inputText id="txt" value="#{adbean.text}" required="true" label="Text 1">
     </p:inputText>  
    
     <p:commandButton update="@form" value="Search" action="#{adbean.doSearchJob(adbean.text)}"/>
        
    <p:dataGrid var="car" value="#{adbean.doSearchJob(adbean.text)}" columns="3" layout="grid"
        rows="12" paginator="true" id="cars"
        paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
        rowsPerPageTemplate="6,12,16">
 
        <f:facet name="header">
            JOB VOLENTEER
        </f:facet>
 
        <p:panel header="#{car.idJobV}" style="text-align:center">
            <h:panelGrid columns="1" style="width:100%">
             
                <h:outputText value="#{car.titre}" />
                
                  <p:graphicImage name="img/#{adbean.jj.image}" width="100" height="50"/> 
 
                <p:commandLink update=":form:carDetail" oncomplete="PF('carDialog').show()" title="View Detail">
                    <h:outputText styleClass="ui-icon ui-icon-search" style="margin:0 auto;" />
                    <f:setPropertyActionListener value="#{car}" target="#{adbean.jj}" />
                </p:commandLink>
            </h:panelGrid>
        </p:panel>
 
    </p:dataGrid>
 
    <p:dialog header="Job Info" widgetVar="carDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
        <p:outputPanel id="carDetail" style="text-align:center;">
            <p:panelGrid  columns="2" rendered="#{not empty adbean.jj}" columnClasses="label,value">
                <f:facet name="header">
                </f:facet>
 
                <h:outputText value="Titre" />
                <h:outputText value="#{adbean.jj.titre}" />
                
 
                <h:outputText value="Date debut" />
                <h:outputText value="#{adbean.jj.dateDebut}" />
 
                <h:outputText value="Date fin" />
                <h:outputText value="#{adbean.jj.dateFin}" style="color:#{dataGridView.selectedCar.color}"/>
 
                <h:outputText value="Description" />
                <h:outputText value="#{adbean.jj.description}" />
                
                 <h:outputText value="Taches" />
                <h:outputText value="#{adbean.jj.taches}" />
                
                <h:outputText value="Lieu" />
                <h:outputText value="#{adbean.jj.lieu}" />
                
                  <p:graphicImage name="img/#{adbean.jj.image}" width="100" height="50"/> 
                

				
				<br></br> 
				
				<p:growl id="growl" showDetail="true" sticky="true" />

							<p:panel>
						
								<p:commandButton value="participate" 
									actionListener="#{growlView.saveMessage(adbean.jj, 1)}" update="growl" />
									
						
							</p:panel>
				
            </p:panelGrid>
        </p:outputPanel>
    </p:dialog>
</h:form>


</h:body>
</html>