EasyMission-web/src/main/java/tn/esprit/EasyMission/presentation/mbeans/UserMangementBean.java
package tn.esprit.EasyMission.presentation.mbeans;



import java.io.Serializable;

import javax.ejb.EJB;
//import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import tn.esprit.EasyMission.Entity.AppUser;
import tn.esprit.EasyMission.iBusiness.IAppUserServiceRemote;


@ManagedBean
@SessionScoped
public class UserMangementBean implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	IAppUserServiceRemote basicOpsLocal ;
	
	private Boolean loggedInAsAgent = false;
	private AppUser user = new AppUser();
	private boolean isLogged;

	public String logout() {
		isLogged = false;
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		return "/login?faces-redirect=true";
	}
	public String doLogin() {
		String navigateTo = "";
		AppUser userLoggedIn = basicOpsLocal.authentification(user.getNom(), user.getPassword());
		if (userLoggedIn != null) {
			isLogged = true;
			user = userLoggedIn;
			HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
			session.setAttribute("user", user);
			
			AppUser us1= (AppUser)session.getAttribute("user");
		//	System.out.println("oooooooooooooooooooooooooooooooooooooooooooooooooo "+us1.getFirstname());
			if (userLoggedIn instanceof AppUser) {
				navigateTo = "/iFrame/add?faces-redirect=true";
			}else {
				loggedInAsAgent = true;
				navigateTo = "/iFrame/showClient?faces-redirect=true";
			
				}
		} else {
			loggedInAsAgent = false;
			navigateTo = "erreur?faces-redirect=true";
		
			System.err.println("not");
		}
		return navigateTo;
	}
	
	
	
	public IAppUserServiceRemote getBasicOpsLocal() {
		return basicOpsLocal;
	}
	public void setBasicOpsLocal(IAppUserServiceRemote basicOpsLocal) {
		this.basicOpsLocal = basicOpsLocal;
	}
	public Boolean getLoggedInAsAgent() {
		return loggedInAsAgent;
	}
	public void setLoggedInAsAgent(Boolean loggedInAsAgent) {
		this.loggedInAsAgent = loggedInAsAgent;
	}
	public AppUser getUser() {
		return user;
	}
	public void setUser(AppUser user) {
		this.user = user;
	}
	public boolean isLogged() {
		return isLogged;
	}
	public void setLogged(boolean isLogged) {
		this.isLogged = isLogged;
	}


}

EasyMission-web/src/main/webapp/WEB-INF/template/client-nav.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui">

	<h:form rendered="#{identity.loggedInAsTeacher}">
		<h:panelGrid columns="2" id="sidebar">
			<h:commandLink action="addCourse" value="add course" />
			<br />
			<h:commandLink action="courseManagement" value="manage courses" />
		</h:panelGrid>
	</h:form>
	<h:form rendered="#{identity.loggedInAsStudent}">
		<h:panelGrid columns="2">
			<h:commandLink action="/pages/studentHome/myCourses?faces-redirect=true"
				value="My Courses" />
			<h:commandLink action="/pages/studentHome/subscription?faces-redirect=true"
				value="Suscribe" />
		</h:panelGrid>
	</h:form>

</ui:composition>

EasyMission-web/src/main/webapp/WEB-INF/template/identity.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui">

	<h:form rendered="#{userMangementBean.logged}">
		<h:panelGrid columns="2">
			<h:outputText value="Logged in as #{userMangementBean.user.username}" />
			<p:commandButton action="#{userMangementBean.logout()}" ajax="false"
				value="Logout" />
		</h:panelGrid>
	</h:form>

</ui:composition>

EasyMission-web/src/main/webapp/WEB-INF/template/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
	<title><ui:insert name="title" /></title>
	<h:outputStylesheet library="css" name="style.css" />
</h:head>
<h:body>

	<div id="container">
		<table id="identity-nav">
			<tr>
				<td>
					<div>
						<ui:include src="/WEB-INF/template/identity.xhtml" />
					</div>
				</td>
			</tr>

		</table>
		<div>
			<!-- <ui:include src="/WEB-INF/template/client-nav.xhtml" /> -->
		</div>


		<div id="content">

			<ui:insert name="content">
</ui:insert>


			
		</div>
		<div id="footer">
			<h3>
				<i>OpenLab Project(B1) Java EE - ESPRIT 2017</i>
			</h3>
		</div>
	</div>
</h:body>
</html>